### ISSUE TITLE
unable to view complex model(zip)

### ISSUE THREAD

**Issue by libvarun** [autodesk-platform-services/aps-simple-viewer-nodejs#12]
same model can be viewed in oss-manager.autodesk.io, but not in this sample.

**Comment by petrbroz** [comment]
Do we have any details as to why the app is unable to view the model?

- perhaps it's a file size limit when the zip file is uploaded to the Node.js server (the default file size limit of [formidable](https://www.npmjs.com/package/formidable) seems to be 200MB)?
- perhaps some issue with uploading the zip file to the Data Management service?
- or a problem with Model Derivative service not being able to translate the design?

**Comment by petrbroz** [comment]
Btw I've just disabled the max upload file size limit in https://github.com/autodesk-platform-services/aps-simple-viewer-nodejs/commit/204b079144e1c82f7a66660f90ffe42059197a31. If the problems persist, please reopen this issue and provide more details.
