### ISSUE TITLE
Persistent markup not working for Type SVG STAMP

### ISSUE THREAD

**Issue by rahulbhardwaj1721** [autodesk-platform-services/aps-simple-viewer-nodejs#13]
I have downloaded the code and run it locally.
All the markup GUI extension type is working except the SVG stamp.
I can save the data, but it's not working when showing the saved SVG stamp .
It's always blank.
Please have a look and let me know the resolution for the same.
Branch name :https://github.com/autodesk-platform-services/aps-simple-viewer-nodejs/tree/markups-persist

**Comment by petrbroz** [comment]
Hi @rahulbhardwaj1721. This is a known limitation. The current implementation of the markup extension is able to _serialize_ stamps (and any custom markups) into the SVG string but it is not able to _parse_ them. You could work around this limitation by serializing and/or parsing stamps and custom markups separately, and adding them back to the overlay programmatically using the markup extension API.
