### ISSUE TITLE
Simple Viewer not loading model if running server locally on 127.0.0.1 + potential solution

### ISSUE THREAD

**Issue by crotundu** [autodesk-platform-services/aps-simple-viewer-nodejs#14]
Hello,

Thank you for putting together this app, it was very helpful understanding how the Simple Viewer works.
Running it locally, as it is, I had an issue, though: I was able to upload models, but I was never able to view them. All I had was a silent (console) error:
<img width="1004" alt="Screenshot 2023-09-04 at 23 11 18" src="https://github.com/autodesk-platform-services/aps-simple-viewer-nodejs/assets/1614658/47dfa42d-b274-4137-ad2a-75c2c55c7581">

It didn't look like the Node.js server was handling that route (nor that it should) so I started digging (the viewer sourcemaps helped, thank you!)

What I found was this part in **envinit.js** file of the viewer library with the block that's attempting to guess the environment based on the hostname:
<img width="630" alt="Screenshot 2023-09-04 at 23 16 43" src="https://github.com/autodesk-platform-services/aps-simple-viewer-nodejs/assets/1614658/a4e900ba-6dbf-4a62-803b-d398985fb2f9">

If someone runs the demo on 127.0.0.0:8080 the viewer will assume that the APS backend is also running locally. Not for localhost:8080 though - maybe it was intentional.

I was able to explicitly set the environment myself to `"AutodeskProduction"` in the **viewer.js** file of the sample app via:
 ```
 Autodesk.Viewing.Initializer(
      { getAccessToken, env: 'AutodeskProduction' }, ...)
```
Unless someone is actively developing the viewer library, it can always be set to 'AutodeskProduction'.

What are your thoughts on this?

Thank you!

**Comment by petrbroz** [comment]
Thank you @crotundu, good catch! I believe we should set `env: "AutodeskProduction"` explicitly to avoid these kinds of gotchas. Let me take care of that.

**Comment by petrbroz** [comment]
Fixed in https://github.com/autodesk-platform-services/aps-simple-viewer-nodejs/commit/d6c6501afcca529e273fda2b709c1e797b2be300.
