### ISSUE TITLE
Uncaught (in promise) #<Object>

### ISSUE THREAD

**Issue by miguelGTailorbird** [autodesk-platform-services/aps-simple-viewer-nodejs#16]
Hi everyone,
I'm looking to embed the viewer in a flutter mobile app. When passing the boilerplate code from the aps tutorial website I came up with this error:

"Uncaught (in promise) #<Object>", source: file:///android_asset/flutter_assets/assets/js-forge-viewer/index.html

that line points to the load method:
![image](https://github.com/autodesk-platform-services/aps-simple-viewer-nodejs/assets/119082131/408700fb-3ec5-42e9-a854-fcca991dca79)

it's not calling the loadSuccess callback but the failure one.
Any thoughts on this one?

regards

**Comment by petrbroz** [comment]
We'll need more information in order to be able to help. The error callback is called with at least two arguments: an error code, and an error message. Try and find out what those are, and share those here please.

**Comment by MiguelG97** [comment]
Closing thread since it was related to the flutter side
