### ISSUE TITLE
aps-simple-viewer-nodejs.autodesk.io is not working

### ISSUE THREAD

**Issue by wuyufei88** [autodesk-platform-services/aps-simple-viewer-nodejs#23]
aps-simple-viewer-nodejs.autodesk.io is not working

**Comment by yiskang** [comment]
Hi @wuyufei88,

It looks fine on my side.

<img width="1610" alt="image" src="https://github.com/autodesk-platform-services/aps-simple-viewer-nodejs/assets/5725083/e61720c8-eb3b-4c27-9baf-b2bb0404b06d">

**Comment by petrbroz** [comment]
@wuyufei88 it looks like you posted this issue on Sunday? Please note that we typically rebuild and restart all of our *.autodesk.io demos (incl. restarting the demo server itself) on weekends to roll in security patches.

**Comment by wuyufei88** [comment]
@petrbroz  ok，it works，thanks
