### ISSUE TITLE
My code doesn't work

### ISSUE THREAD

**Issue by fc88804DOTcn** [autodesk-platform-services/aps-simple-viewer-nodejs#25]
Hi guys! Why did the access_token that i get by 【service.getPublicToken()】 OR【 service.getInternalToken】 in service.ensureBucketExists  doesn't work。it throw an exception "Please provide a valid access token or an authentication provider"；My access_token and screenshot is  following。I thought the reason is APS banned my code callback from computer address just now ，and i add 3 address to the white list, but doesn't work too。That's all. Thank you very much。

"dependencies": {
    "@aps_sdk/authentication": "1.0.0-beta.1",
    "@aps_sdk/autodesk-sdkmanager": "1.0.0-beta.2",
    "@aps_sdk/model-derivative": "1.0.0-beta.3",
    "@aps_sdk/oss": "1.0.0-beta.2",
    "cookie-parser": "~1.4.4",
    "cors": "^2.8.5",
    "debug": "~2.6.9",
    "dotenv": "^16.4.1",
    "express": "~4.16.1",
    "express-formidable": "^1.2.0",
    "http-errors": "~1.6.3",
    "jade": "~1.11.0",
    "morgan": "~1.9.1"
  }

'eyJhbGciOiJSUzI1NiIsImtpZCI6IlhrUFpfSmhoXzlTYzNZS01oRERBZFBWeFowOF9SUzI1NiIsInBpLmF0bSI6ImFzc2MifQ.eyJzY29wZSI6WyJkYXRhOnJlYWQiXSwiY2xpZW50X2lkIjoiT2xBTHk3UUFaTHN3VnRFWXF3ak9mTjNtTXFidDhETUEiLCJpc3MiOiJodHRwczovL2RldmVsb3Blci5hcGkuYXV0b2Rlc2suY29tIiwiYXVkIjoiaHR0cHM6Ly9hdXRvZGVzay5jb20iLCJqdGkiOiJLR2NwVllPczF4eXlYb05WRW8zbG5KNFNMMXA1azM0dW5VVWl0cTRuSnJJSXhQSUc3OVRyQ0ZOTzV6b05OVlhWIiwiZXhwIjoxNzI2MTkzODc4fQ.G_BHSRf8TVDv8In1urQuvRXngkb7kM2QnYvWbQTMRCRwqJr39DOk1sr7M7yAOT4G4o1jQSFi9lR4rIN6vv0Oyv7HqSQN1incaLCNh3bhvDZxsvMSd5YeXihIlwSUNlpXb5z_Dwmo-8KNExhkjJj6v3uGB4Hh6RlUFbLASE1mzkpSj3XhbNlvTfxDhixaunVDKjXBDaMCJFLuNQDKlwaMJfwr-9Qo2xxZp1MwYPZA_Nfy9XzNTqpHbwH9G922zTKK_ihlOtd1-v4wb2ny08dtxjRGeKhLq9MrXOu2o5ovvBZVKKg9dl7IjYQW44MjagiV3dQR5pPH_wBwQ4MYBecE_w'

![图片](https://github.com/user-attachments/assets/35cbb103-71d7-4f07-89cf-2afce251e65d)

![图片](https://github.com/user-attachments/assets/bc1c39fc-505b-42f4-9ce2-fd4ef25f10dd)

![图片](https://github.com/user-attachments/assets/53410e2f-3e44-4391-aa69-0d258bd6f5c6)

**Comment by yiskang** [comment]
Hi @fc88804DOTcn,

Please ensure you have included the OAuth scope  `Scopes.BucketRead` at line 46 of your code for using `getBucketDetails`.

I checked your access token via https://jwt.io/ and noticed that you only have included `Scopes.DataRead` in the access token, which is not enough to run this sample or call `getBucketDetails`. Please refer to https://github.com/autodesk-platform-services/aps-simple-viewer-nodejs/blob/develop/services/aps.js#L15 to add the necessary OAuth scopes.

By the way, this issues tab is for reporting problems or feedback on using this sample, not for SDK use or APS technical questions. Instead, please click `Contact Support` on https://aps.autodesk.com/get-help to create support tickets. We appreciate your cooperation and understanding.

**Comment by fc88804DOTcn** [comment]
> Hi @fc88804DOTcn,
> 
> Please ensure you have included the OAuth scope `Scopes.BucketRead` at line 46 of your code for using `getBucketDetails`.
> 
> I checked your access token via https://jwt.io/ and noticed that you only have included `Scopes.DataRead` in the access token, which is not enough to run this sample or call `getBucketDetails`. Please refer to https://github.com/autodesk-platform-services/aps-simple-viewer-nodejs/blob/develop/services/aps.js#L15 to add the necessary OAuth scopes.
> 
> By the way, this issues tab is for reporting problems or feedback on using this sample, not for SDK use or APS technical questions. Instead, please click `Contact Support` on https://aps.autodesk.com/get-help to create support tickets. We appreciate your cooperation and understanding.

Thank you，i send message on https://aps.autodesk.com/get-help. but the issue is that regardless of whether I use getInternalToken (which includes Scopes.BucketRead) or getPublicToken (which only includes Scopes.DataRead), the response I always receive is about a 'valid access token' being required.
