### ISSUE TITLE
Missing Environment Variables 

### ISSUE THREAD

**Issue by inteldon** [autodesk-platform-services/aps-simple-viewer-nodejs#4]
I downloaded the zip file, extracted it and created a .env file in the root folder, I created a web account, got my credentials as: 
APS_CLIENT_ID="some_string"
APS_CLIENT_SECRET="some_secret"

When I ran the node/yarn start commands I got "Missing some of the environment variables." 

Then I started from scratch, created the project as suggested on Autodesk's getting started page, and I arrived at the same results. I can't get past this step. It's not clear what's missing, the error isn't well defined for me to take next steps. Please assist. Thank you.

**Comment by petrbroz** [comment]
Hi @inteldon, please note that the .env file is only loaded when you start the app using Visual Studio Code. If you want to start your app from the command line, you'll need to specify the environment variables yourself, for example, when bash:

```
APS_CLIENT_ID="..." APS_CLIENT_SECRET="..." yarn start
```
