### ISSUE TITLE
xref, referenced DWG

### ISSUE THREAD

**Issue by lacmuch** [autodesk-platform-services/aps-simple-viewer-nodejs#6]
Can anyone help me how to manage and view the xref referenced DWG files along with the original document?

**Comment by lacmuch** [comment]
OK! :) If I upload the dwg package in one zip, it works....

**Comment by petrbroz** [comment]
Hi @lacmuch, yes, whenever you're working with multiple design files referencing each other, you have two options:
- submit all files in a zip file (as explained in [this tutorial](https://aps.autodesk.com/en/docs/model-derivative/v2/tutorials/translate-zip-to-stl/))
- upload all files individually, and specify the relationships between them using a specific Model Derivative API endpoint (as explained in [this tutorial](https://aps.autodesk.com/en/docs/model-derivative/v2/tutorials/translate-source-file-containing-xref/))
